config/routes.rb
Rails.application.routes.draw do
  get "registrations/new"
  get "registrations/create"
  root to: "pages#home"

  # App Routes
  get "/about" => "about#index"
  get "/static" => "static#index"
  get "/contact" => "contact#index"
  get "/up/", to: "up#index", as: :up
  get "/up/databases", to: "up#databases", as: :up_databases

  # Authentication Routes
  resources :users
  resource :login, controller: :sessions, only: %i[new create destroy]
  resources :passwords, only: %i[new create edit update], param: :token
  get "/login", to: "sessions#new", as: :new_session
  delete "/logout", to: "sessions#destroy", as: :logout
  get "/users" => "users#index"
  get "/signup" => "registrations#new", as: :signup
  post "/signup" => "registrations#create", as: :create_user

  # User profile
  #

  # Admin Routes
  get "/admin", to: "admin#index", as: :admin

  # User Routes
  #

  # User Profile


  # Sidekiq has a web dashboard which you can enable below. It's turned off by
  # default because you very likely wouldn't want this to be available to
  # everyone in production.
  #
  # Uncomment the 2 lines below to enable the dashboard WITHOUT authentication,
  # but be careful because even anonymous web visitors will be able to see it!
  # require "sidekiq/web"
  # mount Sidekiq::Web => "/sidekiq"
  #
  # If you add Devise to this project and happen to have an admin? attribute
  # on your user_page you can uncomment the 4 lines below to only allow access to
  # the dashboard if you're an admin. Feel free to adjust things as needed.
  # require "sidekiq/web"
  # authenticate :user_page, lambda { |u| u.admin? } do
  #   mount Sidekiq::Web => "/sidekiq"
  # end

  # Learn more about this file at: https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :session
  delegate :user, to: :session, allow_nil: true
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :sessions, dependent: :destroy

  normalizes :email_address, with: ->(e) { e.strip.downcase }
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
    @title = "AboutUs"
    @keywords = "about, company values"
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
    render layout: "admin/admin"
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  allow_unauthenticated_access only: :home
  def home
  end
end

app/controllers/up_controller.rb
class UpController < ApplicationController
  allow_unauthenticated_access only: :index
  allow_unauthenticated_access only: :databases
  def index
    head :ok
  end

  def databases
    RedisConn.current.ping
    ActiveRecord::Base.connection.execute("SELECT 1")
    head :ok
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    if session[:user_id]
      @user = User.find_by(id: session[:user_id])
    end
    redirect_to new_session_path unless authenticated?
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/react_helper.rb
module ReactHelper
  def react(component_name, props: {}, **args)
    content_tag(:div, "", data: { react_component: component_name, props: props }, **args)
  end
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/session_helper.rb
module SessionHelper
  def current_user
    if (user_id = session[:user_id])
      user = User.find_by(id: user_id)
      @current_user = user if user
    end
  end

  def current_user?(user)
    user && user == current_user
  end

  def logged_in?
    !current_user.nil?
  end
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/admin/index.html.erb
<%#= render partial: "partials/navbar" %>
<div class="flex justify-center pt-24 pb-12 px-2 sm:px-0">
  <h2 class="text-3xl font-bold text-gray-900 mb-4">Admin Page</h2>
</div>
<%= link_to "Home Page", root_path %>


<p class="text-center text-lg">
<strong>
  <a class="border-b border-gray-900 mb-1" href="https://diveintodocker.com?ref=docker-rails-example">https://diveintodocker.com</a>
</strong>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/admin/admin.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Admin Panel</title>

  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= action_cable_meta_tag %>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="A production ready example Rails app that's using Docker and Docker Compose.">

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  <%= javascript_include_tag "react", "data-turbo-track": "reload", defer: true %>

  <%# Generated with: https://realfavicongenerator.net/ %>
  <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
  <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
  <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
  <link rel="manifest" href="/site.webmanifest">
  <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#61b9d2">
  <meta name="msapplication-TileColor" content="#da532c">
  <meta name="theme-color" content="#ffffff">
</head>

<body class="flex flex-col h-screen justify-between">
<div class="bg-gray-700">
  <div class="max-w-screen-lg mx-auto py-3 px-3 sm:px-6 lg:px-8">
    <div class="flex items-center justify-between flex-wrap">
      <div class="flex-1 flex items-center">
            <span class="flex p-2 rounded-lg bg-gray-900">
              <svg class="w-6 h-6 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path></svg>
            </span>
        <p class="ml-3 font-medium text-white truncate">
          Rails <%= Rails::VERSION::STRING %> and Ruby <%= ENV["RUBY_VERSION"] %>
        </p>
      </div>
      <div class="mt-2 order-3 w-full sm:mt-0 sm:w-auto">
        <div class="rounded-md shadow-xs">
              <span class="flex items-center justify-center px-4 py-2 border border-transparent text-sm leading-5 font-medium rounded-md text-white bg-gray-500">
                RAILS_ENV = <%= Rails.env %>
              </span>
        </div>
      </div>
    </div>
  </div>
</div>
<main class="max-w-screen-lg mx-auto mb-auto">
    <%= yield %>
</main>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Docker + Rails</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= action_cable_meta_tag %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="A production ready example Rails app that's using Docker and Docker Compose.">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= javascript_include_tag "react", "data-turbo-track": "reload", defer: true %>

    <%# Generated with: https://realfavicongenerator.net/ %>
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/site.webmanifest">
    <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#61b9d2">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
  </head>

  <body class=" h-full flex flex-col h-screen justify-between">
    <div class="bg-gray-700">
      <div class="max-w-screen-lg mx-auto py-3 px-3 sm:px-6 lg:px-8">
        <div class="flex items-center justify-between flex-wrap">
          <div class="flex-1 flex items-center">
            <span class="flex p-2 rounded-lg bg-gray-900">
              <svg class="w-6 h-6 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path></svg>
            </span>
            <p class="ml-3 font-medium text-white truncate">
              Rails <%= Rails::VERSION::STRING %> and Ruby <%= ENV["RUBY_VERSION"] %>
            </p>
          </div>
          <div class="mt-2 order-3 w-full sm:mt-0 sm:w-auto">
            <div class="rounded-md shadow-xs">
              <span class="flex items-center justify-center px-4 py-2 border border-transparent text-sm leading-5 font-medium rounded-md text-white bg-gray-500">
                RAILS_ENV = <%= Rails.env %>
              </span>
            </div>
          </div>
        </div>
      </div>
    </div>

    <main class="max-w-screen-lg mx-auto mb-auto">
      <%= yield %>
    </main>

    <footer class="text-center mt-6 pb-6 h-10">
      <p class="text-gray-500">
        <a class="border-b mb-1" href="https://github.com/nickjj/docker-rails-example">Coded</a>
        with
        <svg class="h-5 w-5 text-red-600 inline" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z"></path>
        </svg>
        by
        <a class="border-b mb-1" href="https://nickjanetakis.com">Nick Janetakis</a>
      </p>
    </footer>
  </body>
</html>

app/views/layouts/authentication.html.erb
<!DOCTYPE html>
<html lang="en">
<%= render "shared/components/header" %>
<body class="h-full">
<%= turbo_frame_tag "flash_message"do %>
  <%= render "shared/flash" %>
<% end %>
<main class="body-container h-full ">
  <div class="flex min-h-full">
    <div class="flex relative flex-1 flex-col px-6 py-12
                sm:px-8
                lg:justify-center lg:flex-none lg:px-20
                xl:px-24
                2xl:px-36"
    >
     <div class="w-full text-center mb-6
                lg:absolute lg:top-12 lg:text-left lg_mb-0"
     >
       <%= link_to "/", :class => '' do %>
       Logo here
       <% end %>
     </div>
      <div class="w-full max-w-sm mx-auto lg:w-96 ">
        <h2 class="text-center mb-12 text-3xl lg:text-left lg:mb-8">
          <%= yield(:title) %>
        </h2>
        <%= yield %>
      </div>
    </div>
    <div class="bg-gray-50 dark:bg-gray-900 relative hidden w-0 flex-1 lg:block">

      <% if controller_name == 'registrations' && action_name == new %>
      <div class="absolute z-50 w-full h-full flex-col items-center justify-center">
        <div class="flex h-full flex-col items-center justify-center">
          <div class="mx-auto bg-white dark:bg-gray-900 bg-opacity-30 dark:bg-opacity-80 text-gray-800 dark:text-gray-900">
            <div class="italic font-medium">&ldquo; This is testimonial quote. You should sign up </div>
            <div class="text-sm text-right pr-8 text-gray-400 font-medium">
              <span>Someone's name</span>
            </div>
          </div>
        </div>
      </div>
      <% end %>
      <div class="absolute z-40 top-0 left-0 w-full h-full bg-gray-600 dark:bg-black bg-opacity-40">
<!--        <img src="" alt="" class="">-->
      </div>
    </div>
  </div>
</main>
</body>

app/views/partials/_footer.html.erb
  <footer class="text-center text-lg">
    <strong>
      <p class="border-b border-gray-900 mb-1">This is Footer</p>
    </strong>
  </footer>
  <footer class="text-center mt-6 pb-6 h-10">
    <p class="text-gray-500">
      <a class="border-b mb-1" href="https://github.com/nickjj/docker-rails-example">Coded</a>
      with
      <svg class="h-5 w-5 text-red-600 inline" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z"></path>
      </svg>
      by
      <a class="border-b mb-1" href="https://nickjanetakis.com">Nick Janetakis</a>
    </p>
  </footer>

app/views/partials/_hamburger.html.erb
<!-- Hamburger Toggle BTN -->
<button
  :class="sidebarToggle ? 'lg:bg-transparent dark:lg:bg-transparent bg-gray-100 dark:bg-gray-800' : ''"
  class="z-99999 flex h-10 w-10 items-center justify-center rounded-lg border-gray-200 text-gray-500 lg:h-11 lg:w-11 lg:border dark:border-gray-800 dark:text-gray-400"
  @click.stop="sidebarToggle = !sidebarToggle"
>
  <svg
    class="hidden fill-current lg:block"
    width="16"
    height="12"
    viewBox="0 0 16 12"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      fill-rule="evenodd"
      clip-rule="evenodd"
      d="M0.583252 1C0.583252 0.585788 0.919038 0.25 1.33325 0.25H14.6666C15.0808 0.25 15.4166 0.585786 15.4166 1C15.4166 1.41421 15.0808 1.75 14.6666 1.75L1.33325 1.75C0.919038 1.75 0.583252 1.41422 0.583252 1ZM0.583252 11C0.583252 10.5858 0.919038 10.25 1.33325 10.25L14.6666 10.25C15.0808 10.25 15.4166 10.5858 15.4166 11C15.4166 11.4142 15.0808 11.75 14.6666 11.75L1.33325 11.75C0.919038 11.75 0.583252 11.4142 0.583252 11ZM1.33325 5.25C0.919038 5.25 0.583252 5.58579 0.583252 6C0.583252 6.41421 0.919038 6.75 1.33325 6.75L7.99992 6.75C8.41413 6.75 8.74992 6.41421 8.74992 6C8.74992 5.58579 8.41413 5.25 7.99992 5.25L1.33325 5.25Z"
      fill=""
      />
  </svg>

  <svg
    :class="sidebarToggle ? 'hidden' : 'block lg:hidden'"
    class="fill-current lg:hidden"
    width="24"
    height="24"
    viewBox="0 0 24 24"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      fill-rule="evenodd"
      clip-rule="evenodd"
      d="M3.25 6C3.25 5.58579 3.58579 5.25 4 5.25L20 5.25C20.4142 5.25 20.75 5.58579 20.75 6C20.75 6.41421 20.4142 6.75 20 6.75L4 6.75C3.58579 6.75 3.25 6.41422 3.25 6ZM3.25 18C3.25 17.5858 3.58579 17.25 4 17.25L20 17.25C20.4142 17.25 20.75 17.5858 20.75 18C20.75 18.4142 20.4142 18.75 20 18.75L4 18.75C3.58579 18.75 3.25 18.4142 3.25 18ZM4 11.25C3.58579 11.25 3.25 11.5858 3.25 12C3.25 12.4142 3.58579 12.75 4 12.75L12 12.75C12.4142 12.75 12.75 12.4142 12.75 12C12.75 11.5858 12.4142 11.25 12 11.25L4 11.25Z"
      fill=""
      />
  </svg>

  <!-- cross icon -->
  <svg
    :class="sidebarToggle ? 'block lg:hidden' : 'hidden'"
    class="fill-current"
    width="24"
    height="24"
    viewBox="0 0 24 24"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      fill-rule="evenodd"
      clip-rule="evenodd"
      d="M6.21967 7.28131C5.92678 6.98841 5.92678 6.51354 6.21967 6.22065C6.51256 5.92775 6.98744 5.92775 7.28033 6.22065L11.999 10.9393L16.7176 6.22078C17.0105 5.92789 17.4854 5.92788 17.7782 6.22078C18.0711 6.51367 18.0711 6.98855 17.7782 7.28144L13.0597 12L17.7782 16.7186C18.0711 17.0115 18.0711 17.4863 17.7782 17.7792C17.4854 18.0721 17.0105 18.0721 16.7176 17.7792L11.999 13.0607L7.28033 17.7794C6.98744 18.0722 6.51256 18.0722 6.21967 17.7794C5.92678 17.4865 5.92678 17.0116 6.21967 16.7187L10.9384 12L6.21967 7.28131Z"
      fill=""
      />
  </svg>
</button>
<!-- Hamburger Toggle BTN -->

app/views/partials/_login-form.html.erb
<div class="flex min-h-full flex-col justify-center px-6 py-12 lg:px-8">
  <div class="sm:mx-auto sm:w-full sm:max-w-sm">
    <img class="mx-auto h-10 w-auto" src="https://tailwindcss.com/plus-assets/img/logos/mark.svg?color=indigo&shade=600" alt="Your Company">
    <h2 class="mt-10 text-center text-2xl/9 font-bold tracking-tight text-gray-900">Sign in to your account</h2>
  </div>
  <div class="mt-10 sm:mx-auto sm:w-full sm:max-w-sm">
    <%= form_with url: login_path, :class => 'space-y-6' do |form| %>
      <div>
        <label for="email" class="block text-sm/6 font-medium text-gray-900">Email address</label>
        <div class="mt-2">
          <%= form.email_field :email_address,
                               :class => 'block w-full rounded-md bg-white px-3 py-1.5 text-base text-gray-900 outline-1 -outline-offset-1
                               outline-gray-300 placeholder:text-gray-400 focus:outline-2 focus:-outline-offset-2 focus:outline-indigo-600 sm:text-sm/6',
                               required: true,
                               autofocus: true,
                               autocomplete: "username",
                               value: params[:email_address] %>
        </div>
      </div>
      <div>
        <div class="flex items-center justify-between">
          <label for="password" class="block text-sm/6 font-medium text-gray-900">Password</label>
          <div class="text-sm">
            <%= link_to "Forgot password?", new_password_path,
                        :class => 'font-semibold text-indigo-600 hover:text-indigo-500' %>
          </div>
        </div>
        <div class="mt-2">
          <%= form.password_field :password, :id => 'password',
                                  :class => 'block w-full rounded-md bg-white px-3 py-1.5 text-base text-gray-900 outline-1 -outline-offset-1 outline-gray-300
                                  placeholder:text-gray-400 focus:outline-2 focus:-outline-offset-2 focus:outline-indigo-600 sm:text-sm/6',
                                  required: true,
                                  autocomplete: "current-password",
                                  maxlength: 72 %>
        </div>
        <div>
        </div>
        <%= form.submit "Sign in",
                        :class => 'flex w-full justify-center mt-4 rounded-md bg-indigo-600 px-3 py-1.5 text-sm/6 font-semibold text-white shadow-xs
                        hover:bg-indigo-500 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600' %>
      </div>
      <p>You don't have account? Please <%= link_to "Sign Up", signup_path, :class => 'text-indigo-800 font-semibold py-2 px-4' %></p>
    <% end %>
  </div>
</div>

app/views/partials/_registration-form.html.erb
<div class="min-w-4xl max-sm:max-w-lg mx-auto p-6 mt-6 bg-white">
  <% if alert == flash[:alert] %>
    <p class="py-2 px-3 bg-red-50 mb-5 text-red-500 font-medium rounded-lg inline-block" id="alert"><%= alert %></p>
  <% end %>
  <% if notice == flash[:notice] %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>
  <div class="text-center mb-12 sm:mb-16">
    <img class="mx-auto h-10 w-auto" src="https://tailwindcss.com/plus-assets/img/logos/mark.svg?color=indigo&shade=600" alt="Your Company">
    <h2 class="mt-10 text-center text-2xl/9 font-bold tracking-tight text-gray-900">Sign up to your account</h2>
  </div>
  <%= form_with model: @user, url: signup_url, class: "contents" do |form| %>
    <div class="grid sm:grid-cols-2 gap-8">
      <div>
        <label class="text-slate-800 text-sm font-medium mb-2 block">First Name</label>
        <%= form.text_field :first_name, required: true, autofocus: true, autocomplete: "first_name",
                             placeholder: "Enter your first name",
                             value: params[:first_name],
                             :class => "bg-slate-100 w-full text-slate-800 text-sm px-4 py-3 rounded focus:bg-transparent outline-blue-500 transition-all" %>
      </div>
      <div>
        <label class="text-slate-800 text-sm font-medium mb-2 block">Last Name</label>
        <%= form.text_field :last_name, required: true, autocomplete: "last_name",
                            value: params[:last_name],
                            placeholder: "Enter your Last Name", maxlength: 72,
                           :class => "bg-slate-100 w-full text-slate-800 text-sm px-4 py-3 rounded focus:bg-transparent outline-blue-500 transition-all" %>
      </div>
      <div>
        <label class="text-slate-800 text-sm font-medium mb-2 block">Email Id</label>
        <%= form.email_field :email_address, required: true, autofocus: true, autocomplete: "email", placeholder: "Enter your email address",
                             value: params[:email_address],
                             :class => "bg-slate-100 w-full text-slate-800 text-sm px-4 py-3 rounded focus:bg-transparent outline-blue-500 transition-all" %>
      </div>
      <div>
        <label class="text-slate-800 text-sm font-medium mb-2 block">Mobile No.</label>
        <%= form.text_field :mobile_number, required: false, autofocus: true, placeholder: "Enter your mobile number",
                             value: params[:mobile_number],
                             :class => "bg-slate-100 w-full text-slate-800 text-sm px-4 py-3 rounded focus:bg-transparent outline-blue-500 transition-all" %>
      </div>
      <div>
        <label class="text-slate-800 text-sm font-medium mb-2 block">Password</label>
        <%= form.password_field :password, required: true, autocomplete: "current-password", placeholder: "Enter your password", maxlength: 72,
                                value: params[:password],
                                :class => "bg-slate-100 w-full text-slate-800 text-sm px-4 py-3 rounded focus:bg-transparent outline-blue-500 transition-all" %>
      </div>
      <div>
        <label class="text-slate-800 text-sm font-medium mb-2 block">Confirm Password</label>
        <%= form.password_field :password_confirmation, required: true, autocomplete: "current-password", placeholder: "Enter your password", maxlength: 72,
                                value: params[:password_confirmation],
                                :class => "bg-slate-100 w-full text-slate-800 text-sm px-4 py-3 rounded focus:bg-transparent outline-blue-500 transition-all" %>
      </div>
    </div>
    <div class="mt-12">
      <%=form.submit "Sign Up", :class =>'mx-auto block py-3 px-6 text-sm font-medium tracking-wider rounded text-white bg-blue-600 hover:bg-blue-700 focus:outline-none'%>
    </div>
    <p>You already have account? Please<%= link_to "Sign In", login_path, :class => 'text-indigo-800 font-semibold py-2 px-4' %></p>
  <% end %>
</div>

app/views/shared/components/_header.html.erb
<head>
  <title>Docker + Rails</title>

  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= action_cable_meta_tag %>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="A production ready example Rails app that's using Docker and Docker Compose.">

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  <%= javascript_include_tag "react", "data-turbo-track": "reload", defer: true %>

  <%# Generated with: https://realfavicongenerator.net/ %>
  <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
  <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
  <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
  <link rel="manifest" href="/site.webmanifest">
  <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#61b9d2">
  <meta name="msapplication-TileColor" content="#da532c">
  <meta name="theme-color" content="#ffffff">
</head>